import { Suspense } from "react";
import { Sparkles } from "lucide-react";
import { ChatInterface } from "@/components/chat/chat-interface";
import { ChatSearchSync } from "./chat-search-sync";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Chat with Rishi AI",
  description:
    "Ask Rishi's AI stand-in anything about his experience, skills, or projects. Streaming answers grounded in his résumé.",
};

const SUGGESTIONS = [
  "Tell me about your accessibility work.",
  "What's your biggest project impact so far?",
  "Why should we hire you for a senior React role?",
  "How do you approach performance on a Next.js app?",
  "Walk me through your design system work.",
  "What do you know about WCAG 2.2 AA?",
];

export default function ChatPage() {
  return (
    <div className="container mx-auto max-w-3xl px-4 py-12">
      <header className="mb-6">
        <h1 className="inline-flex items-center gap-2 text-2xl font-semibold tracking-tight">
          <Sparkles className="size-5 text-primary" aria-hidden />
          Chat with Rishi AI
        </h1>
        <p className="mt-2 max-w-2xl text-muted-foreground">
          Ask anything a recruiter would ask. The answers are generated by a small LLM with
          Rishi's actual résumé baked into the system prompt — not a script.
        </p>
      </header>

      <div className="mb-6">
        <p className="mb-2 text-sm font-medium text-muted-foreground">Try a starter question:</p>
        <div className="flex flex-wrap gap-2">
          {SUGGESTIONS.map((s) => (
            <a
              key={s}
              href={`/chat?q=${encodeURIComponent(s)}`}
              className="rounded-full border border-border bg-card px-3 py-1.5 text-xs hover:bg-accent"
            >
              {s}
            </a>
          ))}
        </div>
      </div>

      <Suspense>
        <ChatSearchSync />
      </Suspense>
      <ChatInterface />
    </div>
  );
}
